baseURL = 'https://misstruth.github.io/'
languageCode = 'zh'
title = 'PiDan的个人博客'
theme = 'hugo-theme-ladder'
defaultContentLanguage = "zh"
description = '一个专注于技术分享和生活记录的个人博客'

[pagination]
pagerSize = 10

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/blog/"
weight = 2

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 3

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 4

[[menu.main]]
name = "关于"
url = "/about/"
weight = 5

[[menu.main]]
name = "联系"
url = "/contact/"
weight = 6

[[menu.main]]
name = "网站统计"
url = "/xx/"
weight = 7

[taxonomies]
tag = "tags"
category = "categories"

[params]
brand = "主页"
author = "PiDan"
authorDescription = "阅读｜思考｜产出｜进步"
info = "从未停止对未知的探索，尝试分享一些有趣的东西"
avatarURL = "/images/WechatIMG323.jpg"  # 头像路径，以斜杠开头
darkModeTheme = "data-dark-mode"
favicon = "/images/WechatIMG323.jpg"  # 网站图标路径，以斜杠开头

# 网站选项配置
[params.options]
showDarkMode = true          # 显示深色模式切换按钮
enableImgZooming = true      # 启用图片缩放功能
enableMultiLang = false      # 多语言支持
showMetaTags = true          # 显示文章元信息

# 社交媒体链接
[[params.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/misstruth"
